### ISSUE TITLE
Todo June 2023

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTFlows.jl#4]
- [x] integrate `CTBase` v0.7
- [x] refactor code: one file by kind of flows
- [x] make possible to call an OCFS
- [x] handle Variable case
~~- [ ] add flows from ocp and other control, constraints... cf. use cases in CTProblems~~
- [x] check scalar/vectorial usage: this should reduce the length of the code
- [x] add integration of anything, like matrices, passing by a function, that is function is not for Hamiltonian anymore
- [x] use `AbstractHamiltonian`

**Comment by ocots** [comment]
- use `AbstractHamiltonian`

**Comment by ocots** [comment]
Review concatenation to insure consistency in types
